### Variables
@baseUrl = http://localhost:8080
@contentType = application/json
@actor = user
@commandId = 8b48bfce-6f22-454d-aa2d-28d4c2712371

###############################################
# COMMANDS
###############################################

### Create User - Melania
POST {{baseUrl}}/api/commands/users/create HTTP/1.1
Content-Type: {{contentType}}

{
  "username": "melania",
  "email": "melania@example.com",
  "actor": "{{actor}}"
}

### Create User - John
POST {{baseUrl}}/api/commands/users/create HTTP/1.1
Content-Type: {{contentType}}

{
  "username": "galileo",
  "email": "galileo@example.com",
  "actor": "{{actor}}"
}

### Delete User
POST {{baseUrl}}/api/commands/users/delete HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "galileo@example.com",
  "actor": "{{actor}}"
}

### Composite Command

POST {{baseUrl}}/api/commands/composite HTTP/1.1
Content-Type: application/json

{
  "actor": "admin",
  "commands": [
  {
    "type": "Sleep",
    "payload": {
      "seconds": 10
      }
    },
    {
      "type": "CreateUser",
      "payload": {
        "username": "john.doe",
        "email": "john.doe@example.com"
      }
    },
    {
      "type": "DeleteUser",
      "payload": {
        "email": "john.doe@example.com"
      }
    }
  ]
}

###############################################
# JOURNAL
###############################################

### Get All Journal Entries
GET {{baseUrl}}/api/journal HTTP/1.1

### Get Journal Entry by Command ID
GET {{baseUrl}}/api/journal/{{commandId}} HTTP/1.1

###############################################
# STATISTICS
###############################################

### Get Commands Statistics
GET {{baseUrl}}/api/statistics/commands HTTP/1.1

### Get Average Time for CreateUserCommand
GET {{baseUrl}}/api/statistics/avg-time/dev.marcotondi.application.CreateUserCommand HTTP/1.1

### Get Average Time for UpdateUserCommand
GET {{baseUrl}}/api/statistics/avg-time/dev.marcotondi.application.UpdateUserCommand HTTP/1.1

### Get Average Time for DeleteUserCommand
GET {{baseUrl}}/api/statistics/avg-time/dev.marcotondi.application.DeleteUserCommand HTTP/1.1
